<<<<<<< HEAD
name: Check SQL Assignment 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
=======
name: Check SQL Assignment Week 3


on:
  workflow_dispatch:
>>>>>>> 30014ed09043fe37d08680cbbace88dff26fb863

jobs:
  test:
    runs-on: ubuntu-latest
    env:
<<<<<<< HEAD
=======
      DB_DATABASE: salesDB
>>>>>>> 30014ed09043fe37d08680cbbace88dff26fb863
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Update and Install MySQL
=======
      - name: Update and install dependencies
>>>>>>> 30014ed09043fe37d08680cbbace88dff26fb863
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server mysql-client -y

<<<<<<< HEAD
      - name: Start MySQL Service
        run: sudo /etc/init.d/mysql start

      - name: Create Initial Demo Database
        run: |
          echo "Creating demo database..."
          mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE demo;"

      - name: Validate SQL Queries
        run: |
          # Ensure answers.sql is present and not empty
          if [ ! -s ./answers.sql ]; then
            echo "The answers.sql file is missing or empty. Please provide your queries."
            exit 1
          fi

          echo "Executing queries from answers.sql..."
          output=$(mysql -u$DB_USER -p$DB_PASSWORD < ./answers.sql 2>&1)

          # Display the captured output
          echo "Execution Output:"
          echo "$output"

          # Check for SQL errors
          if echo "$output" | grep -q "ERROR"; then
            echo "SQL script execution failed due to errors."
            exit 1
          fi

      - name: Verify salesDB was created
        run: |
          if ! mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES LIKE 'salesDB';" | grep -q "salesDB"; then
            echo "Database salesDB was not created. Test failed."
            exit 1
          fi
          echo "Database salesDB exists."

      - name: Verify demo database was dropped
        run: |
          if mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES LIKE 'demo';" | grep -q "demo"; then
            echo "Database demo still exists. Test failed."
            exit 1
          fi
          echo "Database demo was successfully dropped."
=======
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Execute and Test SQL answers
        run: |
              # Check if the answers.sql file exists
              if [ ! -f ./answers.sql ]; then
                echo "The answers.sql file is missing. Failing the workflow."
                exit 1
              fi
        
              # Check if the file is truly empty 
              if ! grep -q '[^[:space:]#]' ./answers.sql; then
                echo "The answers.sql file is empty or contains only comments. Failing the workflow."
                exit 1
              fi
        
              # Run the SQL script
              sudo mysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE < ./answers.sql
        
>>>>>>> 30014ed09043fe37d08680cbbace88dff26fb863
